[project]
name = "youtube-download-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.16.0",
    "yt-dlp>=2025.11.12",
]
