[project]
name = "youtube-downloader-gui"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.16.0",
    "requests>=2.32.5",
    "yt-dlp>=2025.11.12",
]
